### ISSUE TITLE
Ticket not associated to Contract Service

### ISSUE THREAD

**Issue by topcat99** [makeyourcloud/myc-vtiger-customer-portal#4]
HI, i have MYC 0.5 installed and it works very well, however, when a customer adds a ticket and select its contract service, no association between the ticket and the contract service itself is made, so i have to do it manually, I can you help me figure it out why? thank you 
Sigfrido

**Comment by bempensato** [comment]
Hi, thank you for your using our portal and reporting this bug, we have solved right now, you should: 

- Replace the content of your file at path: your-portal-dir/modules/HelpDesk/index.php 
- With the fixed file you can find it here: https://raw.githubusercontent.com/makeyourcloud/myc-vtiger-customer-portal/master/modules/HelpDesk/index.php

Let us know if you have some other problem or difficulty, we are happy to help you!

Kind Regards
MakeYourCloud team.

**Comment by topcat99** [comment]
Wow, thank you, it works perfectly.
Grazie!
